import { Text } from "@chakra-ui/react";
import styles from "./index.module.css";
import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  const session = useSession();

  if (session.status == "unauthenticated") {
    signIn("discord");
  } else {
    if (session.status == "authenticated") {
      router.push("/servers");
    }
  }

  return (
    <>
      <Head>
        <title>Loading...</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Text>Loading dashboard, standby.</Text>
      </main>
    </>
  );
};

export default Home;
